server:
  port: 9001
spring:
  application:
    name: education-user
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/education?characterEncoding=utf-8
    username: root
    password: 1234
  jpa:
    database: MySQL
    show-sql: true
    generate-ddl: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:9000/eureka/
